version: "3.9"

networks:
  coopvote-network:
    driver: bridge

services:
  coopvote-postgres:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "coopvotedb"

    networks:
      - coopvote-network

  coopvote-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456

    networks:
      - coopvote-network

  coopvote:
    image: coopvote
    command: ["/wait-for-it.sh", "-t", "30", "coopvote-postgres:5432", "--", "/wait-for-it.sh", "-t", "30", "coopvote-rabbitmq:5672", "--" , "java", "-jar", "coopvote.jar"]
    environment:
      DB_HOST: coopvote-postgres
      RABBITMQ_HOST: coopvote-rabbitmq
    networks:
      - coopvote-network
    depends_on:
      - coopvote-postgres
      - coopvote-rabbitmq

  coopvote-nginx-proxy:
    build: ./nginx
    image: coopvote-nginx-proxy
    ports:
      - "80:80"
    networks:
      - coopvote-network
    depends_on:
      - coopvote