spring:
  profiles:
    active:
      - prod

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: admin
    password: 123456

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/coopvotedb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /docs.html
    operationsSorter: alpha

---

spring:
  profiles: prod

  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

  datasource:
    url: ${JDBC_DATASOURCE_URL}

  jpa:
    show-sql: true
    generate-ddl: true

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /docs.html
    operationsSorter: alpha